app:
  telegram-token: ${TOKEN}
  rate-limiter:
    enable: true
    limit: 120
    refill-per-minute: 120
  retry-specification:
    back-off-type: fixed
    max-attempts: 3
    delay: 10000
    jitter: 0.5
    codes: 429, 500, 501, 502, 503, 504
  dead-letter-queue-topic:
    name: updates_dlq
    replicas: 1
    partitions: 1
  updates-topic:
    name: updates
    replicas: 1
    partitions: 1

spring:
  application:
    name: bot
  jackson:
    time-zone: UTC

server:
  port: 8090

springdoc:
  swagger-ui:
    path: /swagger-ui

logging:
  config: classpath:log4j2-plain.xml
